//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaTro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHD
    {
        public string MaKH { get; set; }
        public string MaHD { get; set; }
        public Nullable<int> SoDien { get; set; }
        public Nullable<int> SoNuoc { get; set; }
        public Nullable<int> GiaDien { get; set; }
        public Nullable<int> GiaNuoc { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual KhachHang KhachHang { get; set; }

        
    }
}
