//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaTro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSPhong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DSPhong()
        {
            this.HoaDons = new HashSet<HoaDon>();
            this.KhachHangs = new HashSet<KhachHang>();
        }
    
        public string MaPhong { get; set; }
        public string TenPhong { get; set; }
        public Nullable<bool> TinhTrangPhong { get; set; }
        public Nullable<double> GiaTienPhong { get; set; }
        public string HinhPhong { get; set; }
        public string ThongTinChiTietPhong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhachHang> KhachHangs { get; set; }
        public virtual KhachHang khachHang { get; set; }
    }
}
